# -*- coding: utf-8 -*-
"""M31_Lesson 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSQM5RLjvB8TbP4snraL43n8GAFXHsgT

# Game for Lesson 1
"""

explorer_name = input("Enter your name, Space Explorer: ")
mission_number = int(input("Enter your mission number: "))

# Data Types and Variables
is_ready = True # tell students 'True' has to be spelled exactly like this
print(f"Is the player Ready?: {is_ready}")
destination = input("Which planet would you like to explore first? ")

# String operations and output
message = f"Explorer {explorer_name}, you are on mission #{mission_number}."
print(message.upper())
print(f"You are headed to {destination}. Good luck!")

"""# Additional Code"""

# type-coversion
x = "31"
y = int(x)
print(type(x))
print(type(y))

is_ready = True
print(type(is_ready))

print(float(5))

a = float(5)
b = int(5.14)
print(a + b)

